### ISSUE TITLE
El fondo de pantalla no muestra en la interfaz...

### ISSUE THREAD

**Issue by Autinfit** [Autinfit/Fireworks#12]
_No sé cuál era el problema a resolver, compilé correctamente el proyecto, pero creo que me estoy percatando de algo..._

**Comment by MARSFOREVER472** [comment]
_Quizás lo más probable es que faltaba poner el método de configuración tal como tú escribiste un algoritmo sencillo dentro de un constructor que creaste en la clase._

**Comment by Autinfit** [comment]
_Muy buena respuesta, ahora logré resolver este inconveniente, así que gracias por todo, mi estimado!_
